/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { PersonalAssistanceService } from "../personalAssistance.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PersonalAssistanceCreateInput } from "./PersonalAssistanceCreateInput";
import { PersonalAssistance } from "./PersonalAssistance";
import { PersonalAssistanceFindManyArgs } from "./PersonalAssistanceFindManyArgs";
import { PersonalAssistanceWhereUniqueInput } from "./PersonalAssistanceWhereUniqueInput";
import { PersonalAssistanceUpdateInput } from "./PersonalAssistanceUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PersonalAssistanceControllerBase {
  constructor(
    protected readonly service: PersonalAssistanceService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: PersonalAssistance })
  @nestAccessControl.UseRoles({
    resource: "PersonalAssistance",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createPersonalAssistance(
    @common.Body() data: PersonalAssistanceCreateInput
  ): Promise<PersonalAssistance> {
    return await this.service.createPersonalAssistance({
      data: {
        ...data,

        student: data.student
          ? {
              connect: data.student,
            }
          : undefined,
      },
      select: {
        assistanceType: true,
        createdAt: true,
        details: true,
        id: true,

        student: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [PersonalAssistance] })
  @ApiNestedQuery(PersonalAssistanceFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "PersonalAssistance",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async personalAssistances(
    @common.Req() request: Request
  ): Promise<PersonalAssistance[]> {
    const args = plainToClass(PersonalAssistanceFindManyArgs, request.query);
    return this.service.personalAssistances({
      ...args,
      select: {
        assistanceType: true,
        createdAt: true,
        details: true,
        id: true,

        student: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: PersonalAssistance })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PersonalAssistance",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async personalAssistance(
    @common.Param() params: PersonalAssistanceWhereUniqueInput
  ): Promise<PersonalAssistance | null> {
    const result = await this.service.personalAssistance({
      where: params,
      select: {
        assistanceType: true,
        createdAt: true,
        details: true,
        id: true,

        student: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: PersonalAssistance })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PersonalAssistance",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updatePersonalAssistance(
    @common.Param() params: PersonalAssistanceWhereUniqueInput,
    @common.Body() data: PersonalAssistanceUpdateInput
  ): Promise<PersonalAssistance | null> {
    try {
      return await this.service.updatePersonalAssistance({
        where: params,
        data: {
          ...data,

          student: data.student
            ? {
                connect: data.student,
              }
            : undefined,
        },
        select: {
          assistanceType: true,
          createdAt: true,
          details: true,
          id: true,

          student: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: PersonalAssistance })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PersonalAssistance",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deletePersonalAssistance(
    @common.Param() params: PersonalAssistanceWhereUniqueInput
  ): Promise<PersonalAssistance | null> {
    try {
      return await this.service.deletePersonalAssistance({
        where: params,
        select: {
          assistanceType: true,
          createdAt: true,
          details: true,
          id: true,

          student: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
